import type { CourseDetail } from "@/lib/courses"

export type CourseSeed = Pick<CourseDetail, "title" | "tagline" | "description" | "duration" | "students" | "rating" | "badge" | "features"> & {
  badgeColor: string
  eligibility: string[]
  syllabus: CourseDetail["syllabus"]
  benefits: string[]
  fee: string
  batchStart: string
  examPattern: CourseDetail["examPattern"]
}

export const COURSE_SEED_DETAILS: Record<string, CourseSeed> = {
  "nda": {
    id: "nda",
    title: "NDA Course",
    tagline: "Complete Preparation for National Defence Academy",
    description: "Our NDA Course provides comprehensive preparation for the NDA written exam and SSB interview. With expert guidance, rigorous practice, and complete physical training, we ensure you are fully prepared to join the prestigious National Defence Academy.",
    duration: "6–12 Months",
    students: "2,000+",
    rating: 4.8,
    badge: "Best Seller",
    badgeColor: "bg-accent text-accent-foreground",
    eligibility: [
      "Age: 16.5 to 19.5 years",
      "Educational Qualification: 10+2 or equivalent",
      "Unmarried male candidates (Female for Air Force & Navy)",
      "Physical fitness as per NDA standards",
    ],
    syllabus: [
      {
        title: "Mathematics",
        topics: ["Algebra", "Trigonometry", "Calculus", "Matrices & Determinants", "Analytical Geometry", "Statistics & Probability"],
      },
      {
        title: "General Ability",
        topics: ["English", "Physics", "Chemistry", "Biology", "History", "Geography", "Current Affairs"],
      },
      {
        title: "SSB Preparation",
        topics: ["Psychological Tests", "GTO Tasks", "Personal Interview", "Conference"],
      },
    ],
    features: [
      "Expert faculty with military background",
      "Daily physical training sessions",
      "Regular mock tests and assessments",
      "Complete SSB interview preparation",
      "GTO ground training",
      "Personality development classes",
    ],
    benefits: [
      "Proven track record of selections",
      "Individual attention and mentoring",
      "Modern infrastructure and facilities",
      "Hostel accommodation available",
      "Post-selection guidance",
      "Lifetime alumni support",
    ],
    fee: "Contact for fee details",
    batchStart: "New batches every month",
    examPattern: [
      { section: "Mathematics", marks: "300", time: "2.5 hours" },
      { section: "General Ability", marks: "600", time: "2.5 hours" },
      { section: "Total", marks: "900", time: "5 hours" },
    ],
  },
  "nda-foundation": {
    id: "nda-foundation",
    title: "NDA Foundation Course",
    tagline: "Start Your Defence Journey After Class 10",
    description: "Our NDA Foundation Course is an integrated program that combines regular schooling with NDA preparation. Students live and study on campus, following a disciplined schedule that prepares them for both board exams and NDA selection.",
    duration: "2–3 Years",
    students: "500+",
    rating: 4.9,
    badge: "Popular",
    badgeColor: "bg-primary text-primary-foreground",
    eligibility: [
      "Students who have passed Class 10",
      "Age: Below 16 years at joining",
      "Good academic record",
      "Basic physical fitness",
    ],
    syllabus: [
      {
        title: "Academic Curriculum",
        topics: ["Class 11 & 12 CBSE/State Board", "Science Stream (PCM)", "English & General Studies"],
      },
      {
        title: "NDA Preparation",
        topics: ["Mathematics (NDA level)", "General Ability Test", "Logical Reasoning", "Current Affairs"],
      },
      {
        title: "Physical & SSB",
        topics: ["Daily PT sessions", "Sports activities", "GTO basics", "Communication skills"],
      },
    ],
    features: [
      "Integrated schooling with NDA prep",
      "Hostel facility on campus",
      "Daily physical training",
      "Military-style discipline",
      "Board exam preparation",
      "Early SSB exposure",
    ],
    benefits: [
      "Head start over other aspirants",
      "2–3 NDA attempts during course",
      "Holistic personality development",
      "Strong academic foundation",
      "Disciplined lifestyle habits",
      "Long-term mentorship",
    ],
    fee: "Contact for fee details",
    batchStart: "April & July every year",
    examPattern: [
      { section: "Class 11", marks: "As per CBSE", time: "Full year" },
      { section: "Class 12", marks: "As per CBSE", time: "Full year" },
      { section: "NDA Mock Tests", marks: "900", time: "Weekly" },
    ],
  },
  "cds": {
    id: "cds",
    title: "CDS Course",
    tagline: "Combined Defence Services Examination Preparation",
    description: "The CDS Course provides structured preparation for the Combined Defence Services Examination. Our comprehensive program covers all aspects of the written exam and SSB interview preparation.",
    duration: "6 Months",
    students: "1,500+",
    rating: 4.8,
    badge: null,
    badgeColor: "",
    eligibility: [
      "Age: 19 to 25 years (varies by entry)",
      "Graduate degree from recognized university",
      "Unmarried candidates",
      "Physical fitness as per standards",
    ],
    syllabus: [
      {
        title: "English",
        topics: ["Grammar", "Vocabulary", "Comprehension", "Spotting Errors", "Sentence Arrangement"],
      },
      {
        title: "General Knowledge",
        topics: ["Current Affairs", "History", "Geography", "Polity", "Economics", "Science"],
      },
      {
        title: "Mathematics (OTA exempt)",
        topics: ["Arithmetic", "Algebra", "Geometry", "Trigonometry", "Mensuration", "Statistics"],
      },
    ],
    features: [
      "Comprehensive study material",
      "Daily current affairs updates",
      "Regular mock tests",
      "SSB interview training",
      "Physical fitness guidance",
      "Personal interview preparation",
    ],
    benefits: [
      "High selection rate",
      "Experienced faculty",
      "Flexible batch timings",
      "Online and offline modes",
      "Doubt clearing sessions",
      "Performance tracking",
    ],
    fee: "Contact for fee details",
    batchStart: "Monthly new batches",
    examPattern: [
      { section: "English", marks: "100", time: "2 hours" },
      { section: "General Knowledge", marks: "100", time: "2 hours" },
      { section: "Mathematics", marks: "100", time: "2 hours" },
    ],
  },
  "ssb": {
    id: "ssb",
    title: "SSB Interview Training",
    tagline: "21-Day Comprehensive SSB Preparation",
    description: "Our SSB Interview Training is a 21-day intensive program that prepares you for every aspect of the Service Selection Board interview. From psychological tests to GTO tasks, we ensure you develop officer-like qualities.",
    duration: "21 Days",
    students: "3,000+",
    rating: 4.9,
    badge: "Top Rated",
    badgeColor: "bg-accent text-accent-foreground",
    eligibility: [
      "Qualified NDA/CDS/AFCAT written exam",
      "Received SSB call letter",
      "Meeting physical standards",
      "Self-motivated candidates",
    ],
    syllabus: [
      {
        title: "Psychological Tests",
        topics: ["TAT", "WAT", "SRT", "Self Description"],
      },
      {
        title: "GTO Tasks",
        topics: ["GD", "GPE", "PGT", "HGT", "Individual Obstacles", "Command Task", "Final GD"],
      },
      {
        title: "Personal Interview",
        topics: ["Introduction", "Personal Questions", "Technical Questions", "Current Affairs", "Rapid Fire"],
      },
    ],
    features: [
      "Actual GTO ground practice",
      "Mock SSB interviews",
      "Psychology expert guidance",
      "Individual feedback",
      "Physical fitness training",
      "Confidence building",
    ],
    benefits: [
      "Highest recommendation rate",
      "Ex-SSB board members as faculty",
      "Real SSB simulation",
      "Personalized improvement plan",
      "Post-training support",
      "Success stories of students",
    ],
    fee: "Contact for fee details",
    batchStart: "Batches every 10 days",
    examPattern: [
      { section: "Day 1 — Screening", marks: "OIR + PP&DT", time: "Half day" },
      { section: "Day 2–4 — Psychology", marks: "4 Tests", time: "3 days" },
      { section: "Day 2–4 — GTO", marks: "9 Tasks", time: "3 days" },
      { section: "Day 2–4 — Interview", marks: "Personal", time: "45–60 min" },
      { section: "Day 5 — Conference", marks: "Final", time: "Morning" },
    ],
  },
  "afcat": {
    id: "afcat",
    title: "AFCAT Course",
    tagline: "Air Force Common Admission Test Preparation",
    description: "Our AFCAT coaching program provides step-by-step preparation for the Air Force Common Admission Test and AFSB interview. Join the Indian Air Force with our expert guidance.",
    duration: "4–6 Months",
    students: "800+",
    rating: 4.7,
    badge: null,
    badgeColor: "",
    eligibility: [
      "Age: 20 to 24 years",
      "Graduate with 60% in Physics & Maths (for Flying)",
      "Graduate in any discipline (for Ground Duty)",
      "Unmarried candidates",
    ],
    syllabus: [
      {
        title: "General Awareness",
        topics: ["History", "Geography", "Polity", "Economics", "Current Affairs", "Defence News"],
      },
      {
        title: "Verbal Ability",
        topics: ["Comprehension", "Error Detection", "Sentence Completion", "Synonyms & Antonyms"],
      },
      {
        title: "Numerical Ability",
        topics: ["Decimal & Fractions", "Ratio & Proportion", "Profit & Loss", "Time & Distance", "Percentage"],
      },
      {
        title: "Reasoning",
        topics: ["Verbal & Non-Verbal", "Spatial", "Logical", "Series Completion"],
      },
    ],
    features: [
      "Complete AFCAT syllabus coverage",
      "AFSB interview preparation",
      "Physical fitness training",
      "Mock tests series",
      "Current affairs updates",
      "EKT preparation (if applicable)",
    ],
    benefits: [
      "Experienced Air Force mentors",
      "High success rate",
      "Online and offline modes",
      "Flexible batch timings",
      "Study material included",
      "Doubt clearing support",
    ],
    fee: "Contact for fee details",
    batchStart: "New batches monthly",
    examPattern: [
      { section: "General Awareness", marks: "50", time: "Shared" },
      { section: "Verbal Ability", marks: "75", time: "Shared" },
      { section: "Numerical Ability", marks: "50", time: "Shared" },
      { section: "Reasoning", marks: "75", time: "Shared" },
      { section: "Total", marks: "250", time: "2 hours" },
    ],
  },
  "navy-agniveer": {
    id: "navy-agniveer",
    title: "Indian Navy Agniveer",
    tagline: "Navy SSR/AA Examination Preparation",
    description: "Our Indian Navy Agniveer coaching program provides complete preparation for the Navy SSR and AA examinations. We cover written tests, physical fitness, and medical preparation.",
    duration: "3–4 Months",
    students: "600+",
    rating: 4.7,
    badge: "New",
    badgeColor: "bg-primary text-primary-foreground",
    eligibility: [
      "Age: 17.5 to 21 years",
      "10+2 with Maths & Physics (for SSR)",
      "10+2 in any stream (for AA)",
      "Physical & medical fitness",
    ],
    syllabus: [
      {
        title: "English",
        topics: ["Comprehension", "Grammar", "Vocabulary", "Verbal Ability"],
      },
      {
        title: "Science",
        topics: ["Physics", "Chemistry", "Biology basics"],
      },
      {
        title: "Mathematics",
        topics: ["Algebra", "Geometry", "Trigonometry", "Mensuration"],
      },
      {
        title: "General Knowledge",
        topics: ["Current Affairs", "Geography", "History", "Defence Awareness"],
      },
    ],
    features: [
      "Complete syllabus coverage",
      "Physical fitness training",
      "Medical preparation guidance",
      "Mock tests",
      "Documentation assistance",
      "Interview preparation",
    ],
    benefits: [
      "Experienced faculty",
      "High selection rate",
      "Comprehensive preparation",
      "Physical training ground",
      "Hostel facility",
      "Post-selection support",
    ],
    fee: "Contact for fee details",
    batchStart: "Regular batches",
    examPattern: [
      { section: "English", marks: "25", time: "Shared" },
      { section: "Science", marks: "25", time: "Shared" },
      { section: "Mathematics", marks: "25", time: "Shared" },
      { section: "General Knowledge", marks: "25", time: "Shared" },
      { section: "Total", marks: "100", time: "1 hour" },
    ],
  },
  "airforce-xy": {
    id: "airforce-xy",
    title: "Airforce X / Y Group",
    tagline: "Indian Air Force Airmen Selection Preparation",
    description: "Our Airforce X/Y Group coaching provides comprehensive preparation for Indian Air Force Airmen selection. We cover both technical and non-technical streams.",
    duration: "4–6 Months",
    students: "700+",
    rating: 4.6,
    badge: null,
    badgeColor: "",
    eligibility: [
      "Age: 17 to 21 years",
      "10+2 with PCM (for X Group)",
      "10+2 in any stream (for Y Group)",
      "Physical fitness standards",
    ],
    syllabus: [
      {
        title: "English",
        topics: ["Comprehension", "Grammar", "Vocabulary", "Verbal Ability"],
      },
      {
        title: "Physics (X Group)",
        topics: ["Mechanics", "Heat", "Optics", "Electricity", "Modern Physics"],
      },
      {
        title: "Mathematics (X Group)",
        topics: ["Algebra", "Trigonometry", "Calculus", "Coordinate Geometry"],
      },
      {
        title: "Reasoning (Y Group)",
        topics: ["Verbal Reasoning", "Non-Verbal Reasoning", "Series", "Analogy"],
      },
    ],
    features: [
      "Separate X and Y Group batches",
      "Complete syllabus coverage",
      "Physical fitness training",
      "Mock tests",
      "Interview preparation",
      "Medical guidance",
    ],
    benefits: [
      "Experienced technical faculty",
      "High success rate",
      "Comprehensive study material",
      "Practice test series",
      "Doubt clearing sessions",
      "Physical training ground",
    ],
    fee: "Contact for fee details",
    batchStart: "Regular batches",
    examPattern: [
      { section: "English", marks: "20", time: "Shared" },
      { section: "Physics", marks: "25", time: "Shared" },
      { section: "Mathematics", marks: "25", time: "Shared" },
      { section: "Total (X Group)", marks: "70", time: "60 min" },
    ],
  },
  "mns": {
    id: "mns",
    title: "MNS Course",
    tagline: "Military Nursing Service Preparation",
    description: "Our MNS course provides complete preparation for the Military Nursing Service examination. We cover NEET preparation, MNS written exam, and interview training.",
    duration: "3–6 Months",
    students: "400+",
    rating: 4.8,
    badge: "For Women",
    badgeColor: "bg-[#7c3aed] text-white",
    eligibility: [
      "Age: 17 to 25 years",
      "Female candidates only",
      "10+2 with PCB",
      "NEET qualification",
      "Physical & medical fitness",
    ],
    syllabus: [
      {
        title: "NEET Preparation",
        topics: ["Physics", "Chemistry", "Biology", "NEET mock tests"],
      },
      {
        title: "General English",
        topics: ["Grammar", "Comprehension", "Vocabulary", "Essay writing"],
      },
      {
        title: "General Intelligence",
        topics: ["Reasoning", "Problem solving", "Analytical ability"],
      },
      {
        title: "Interview Preparation",
        topics: ["Personal interview", "Medical knowledge", "Current affairs"],
      },
    ],
    features: [
      "NEET + MNS integrated prep",
      "Experienced medical faculty",
      "Interview training",
      "Physical fitness guidance",
      "Mock tests",
      "Medical knowledge sessions",
    ],
    benefits: [
      "High success rate",
      "Comprehensive preparation",
      "Female-friendly environment",
      "Hostel facility",
      "Post-selection guidance",
      "Career counseling",
    ],
    fee: "Contact for fee details",
    batchStart: "Annual batches",
    examPattern: [
      { section: "NEET Score", marks: "Qualifying", time: "As per NTA" },
      { section: "Personal Interview", marks: "Merit based", time: "15–20 min" },
      { section: "Medical Examination", marks: "Qualifying", time: "As scheduled" },
    ],
  },
  "territorial-army": {
    id: "territorial-army",
    title: "Territorial Army Officer",
    tagline: "Serve the Nation While Pursuing Your Career",
    description: "The Territorial Army provides an opportunity for working professionals to serve the nation in uniform while continuing their primary occupation. Our program prepares candidates for the written examination and SSB interview.",
    duration: "3 Months",
    students: "400+",
    rating: 4.8,
    badge: null,
    badgeColor: "",
    eligibility: [
      "Age: 18 to 42 years",
      "Graduate from recognized university",
      "Employed in Central/State Govt. or Private Sector",
      "Physical fitness as per Army standards",
    ],
    syllabus: [
      {
        title: "Reasoning",
        topics: ["Verbal Reasoning", "Non-Verbal Reasoning", "Analytical Reasoning", "Problem Solving"],
      },
      {
        title: "Elementary Mathematics",
        topics: ["Arithmetic", "Algebra", "Geometry", "Statistics", "Mensuration"],
      },
      {
        title: "General Knowledge",
        topics: ["History", "Geography", "Polity", "Economics", "Current Affairs", "Defence Knowledge"],
      },
      {
        title: "English",
        topics: ["Grammar", "Vocabulary", "Comprehension", "Usage"],
      },
    ],
    features: [
      "Weekend batch option available",
      "Flexible timing for working professionals",
      "Complete syllabus coverage",
      "SSB interview preparation",
      "Online doubt sessions",
      "Mock tests series",
    ],
    benefits: [
      "Working professional friendly",
      "Experienced faculty",
      "High success rate",
      "Online and offline modes",
      "Post-selection guidance",
      "Alumni network",
    ],
    fee: "Contact for fee details",
    batchStart: "February & August",
    examPattern: [
      { section: "Reasoning", marks: "50", time: "Shared" },
      { section: "Elementary Mathematics", marks: "50", time: "Shared" },
      { section: "General Knowledge", marks: "50", time: "Shared" },
      { section: "English", marks: "50", time: "Shared" },
      { section: "Total", marks: "200", time: "2 hours" },
    ],
  },
  "navy": {
    id: "navy",
    title: "Indian Navy Recruitment",
    tagline: "Join the Indian Navy — Sailors Entry",
    description: "Complete preparation for Indian Navy recruitment examinations including MR, AA, and SSR with physical fitness training.",
    duration: "4 Months",
    students: "600+",
    rating: 4.7,
    badge: null,
    badgeColor: "",
    eligibility: [
      "Age: 17 to 21 years",
      "10th/12th Pass (as per entry)",
      "Physical & Medical fitness",
      "Swimming ability preferred",
    ],
    syllabus: [
      {
        title: "Mathematics",
        topics: ["Simplification", "Algebra", "Geometry", "Mensuration", "Trigonometry"],
      },
      {
        title: "Science",
        topics: ["Physics Fundamentals", "Chemistry Basics", "Biology Essentials"],
      },
      {
        title: "English",
        topics: ["Grammar", "Vocabulary", "Comprehension", "Common Errors"],
      },
      {
        title: "General Knowledge",
        topics: ["Geography", "History", "Current Affairs", "Naval Knowledge"],
      },
    ],
    features: [
      "Entry-specific preparation",
      "Physical fitness training",
      "Swimming training",
      "Mock tests & analysis",
      "Medical test guidance",
      "Document verification support",
    ],
    benefits: [
      "Experienced faculty",
      "High selection rate",
      "Hostel facility",
      "Complete preparation",
      "Physical training ground",
      "Post-selection support",
    ],
    fee: "Contact for fee details",
    batchStart: "Every Month",
    examPattern: [
      { section: "English", marks: "25", time: "Shared" },
      { section: "Science", marks: "25", time: "Shared" },
      { section: "Mathematics", marks: "25", time: "Shared" },
      { section: "General Knowledge", marks: "25", time: "Shared" },
      { section: "Total", marks: "100", time: "1 hour" },
    ],
  },
}

