export const courses = [
  {
    slug: "nda",
    title: "NDA Foundation Course",
    subtitle: "National Defence Academy",
    description: "Comprehensive preparation for NDA written examination and SSB interview. This course covers complete syllabus with focus on Mathematics and General Ability Test.",
    longDescription: "The National Defence Academy (NDA) is the Joint Services academy of the Indian Armed Forces, where cadets of the three services train together before they go on to respective service academies for further pre-commissioning training. Our NDA Foundation Course is designed to provide comprehensive preparation that covers every aspect of the NDA examination.",
    duration: "12 Months",
    eligibility: "Class 11th/12th Students (Science/Commerce/Arts)",
    ageLimit: "16.5 to 19.5 years",
    fee: "₹85,000",
    batchSize: "30 Students",
    startDate: "Every Month",
    image: "/placeholder.svg?height=400&width=600",
    icon: "Shield",
    color: "primary",
    features: [
      "Complete Mathematics coverage (300 marks)",
      "General Ability Test preparation",
      "English & General Knowledge",
      "Weekly mock tests & analysis",
      "SSB interview preparation included",
      "Physical training guidance",
      "Doubt clearing sessions",
      "Study material provided",
    ],
    syllabus: [
      {
        title: "Mathematics",
        topics: ["Algebra", "Matrices & Determinants", "Trigonometry", "Analytical Geometry", "Differential Calculus", "Integral Calculus", "Vector Algebra", "Statistics & Probability"],
      },
      {
        title: "General Ability Test - English",
        topics: ["Grammar & Usage", "Vocabulary", "Comprehension", "Cohesion in Paragraph", "Spotting Errors", "Sentence Improvement", "Synonyms & Antonyms"],
      },
      {
        title: "General Knowledge",
        topics: ["Physics", "Chemistry", "Biology", "History", "Geography", "Current Affairs", "Defence & Security"],
      },
    ],
    schedule: {
      weekdays: "6:00 AM - 8:00 AM (Physical Training), 9:00 AM - 5:00 PM (Academic Sessions)",
      weekends: "Mock Tests & Analysis Sessions",
    },
    mentors: ["Col. Rajesh Kumar (Retd.)", "Prof. Amit Sharma", "Capt. Vikram Yadav"],
  },
  {
    slug: "cds",
    title: "CDS Coaching Program",
    subtitle: "Combined Defence Services",
    description: "Expert coaching for CDS examination covering all three papers - English, General Knowledge, and Elementary Mathematics with SSB preparation.",
    longDescription: "The Combined Defence Services (CDS) Examination is conducted by UPSC for recruitment into the Indian Military Academy, Officers Training Academy, Indian Naval Academy, and Indian Air Force Academy. Our CDS Coaching Program is meticulously designed to help graduates crack this competitive examination.",
    duration: "6 Months",
    eligibility: "Graduates from any recognized university",
    ageLimit: "19 to 25 years",
    fee: "₹55,000",
    batchSize: "25 Students",
    startDate: "January & July",
    image: "/placeholder.svg?height=400&width=600",
    icon: "Target",
    color: "accent",
    features: [
      "Complete syllabus coverage",
      "English proficiency training",
      "General Knowledge with current affairs",
      "Elementary Mathematics",
      "Previous year paper analysis",
      "SSB interview coaching",
      "Weekly assessments",
      "One-on-one mentoring",
    ],
    syllabus: [
      {
        title: "English",
        topics: ["Comprehension", "Grammar", "Vocabulary", "Sentence Arrangement", "Error Detection", "Fill in the Blanks", "Idioms & Phrases"],
      },
      {
        title: "General Knowledge",
        topics: ["History", "Geography", "Economics", "Polity", "Science", "Current Affairs", "Defence Knowledge"],
      },
      {
        title: "Elementary Mathematics",
        topics: ["Number System", "Algebra", "Trigonometry", "Geometry", "Mensuration", "Statistics"],
      },
    ],
    schedule: {
      weekdays: "9:00 AM - 4:00 PM (Academic Sessions)",
      weekends: "Mock Tests & Doubt Sessions",
    },
    mentors: ["Maj. Priya Singh (Retd.)", "Prof. Neha Verma", "Lt. Col. Sanjay Gupta (Retd.)"],
  },
  {
    slug: "afcat",
    title: "AFCAT Excellence Program",
    subtitle: "Air Force Common Admission Test",
    description: "Specialized training for AFCAT examination with focus on General Awareness, Verbal Ability, Numerical Ability, and Reasoning.",
    longDescription: "The Air Force Common Admission Test (AFCAT) is conducted by the Indian Air Force for recruitment of officers in Flying, Technical, and Ground Duty branches. Our AFCAT Excellence Program provides focused preparation to help you achieve your dream of joining the Indian Air Force.",
    duration: "4 Months",
    eligibility: "Graduates (60% in Physics & Maths for Technical)",
    ageLimit: "20 to 24 years",
    fee: "₹45,000",
    batchSize: "20 Students",
    startDate: "March & September",
    image: "/placeholder.svg?height=400&width=600",
    icon: "Plane",
    color: "primary",
    features: [
      "AFCAT exam pattern mastery",
      "General Awareness enhancement",
      "Verbal Ability & English",
      "Numerical Ability training",
      "Reasoning & Military Aptitude",
      "EKT preparation (Technical branch)",
      "AFSB interview preparation",
      "Mock tests with analysis",
    ],
    syllabus: [
      {
        title: "General Awareness",
        topics: ["History", "Geography", "Civics", "Politics", "Current Affairs", "Sports", "Books & Authors", "Art & Culture"],
      },
      {
        title: "Verbal Ability",
        topics: ["Comprehension", "Error Detection", "Sentence Completion", "Synonyms & Antonyms", "Idioms & Phrases"],
      },
      {
        title: "Numerical Ability",
        topics: ["Decimal & Fractions", "Ratio & Proportion", "Average", "Percentage", "Simple Interest", "Time & Distance"],
      },
      {
        title: "Reasoning & Military Aptitude",
        topics: ["Verbal & Non-verbal Reasoning", "Spatial Ability", "Military Aptitude Test"],
      },
    ],
    schedule: {
      weekdays: "10:00 AM - 4:00 PM (Academic Sessions)",
      weekends: "Practice Tests & Analysis",
    },
    mentors: ["Wg. Cdr. Arun Mehta (Retd.)", "Prof. Kavita Sharma", "Sqn. Ldr. Ravi Kumar (Retd.)"],
  },
  {
    slug: "ssb",
    title: "SSB Interview Preparation",
    subtitle: "Services Selection Board",
    description: "Intensive SSB interview preparation covering psychological tests, group testing, and personal interview with mock SSB sessions.",
    longDescription: "The Services Selection Board (SSB) Interview is the final and most crucial stage of selection for all defence services. Our SSB Interview Preparation program is designed by ex-SSB assessors and successful candidates to help you develop the Officer Like Qualities (OLQs) required to clear this challenging assessment.",
    duration: "3 Weeks Intensive",
    eligibility: "Written exam qualified candidates",
    ageLimit: "As per exam",
    fee: "₹35,000",
    batchSize: "15 Students",
    startDate: "Multiple batches monthly",
    image: "/placeholder.svg?height=400&width=600",
    icon: "Users",
    color: "accent",
    features: [
      "Complete 5-day SSB simulation",
      "Psychological tests training",
      "Group Testing (GTO) practice",
      "Personal Interview preparation",
      "OLQ development program",
      "Mock SSB with feedback",
      "Individual personality development",
      "Conference preparation",
    ],
    syllabus: [
      {
        title: "Day 1 - Screening",
        topics: ["Officer Intelligence Rating (OIR)", "Picture Perception & Description Test (PPDT)", "Group Discussion"],
      },
      {
        title: "Day 2 - Psychological Tests",
        topics: ["Thematic Apperception Test (TAT)", "Word Association Test (WAT)", "Situation Reaction Test (SRT)", "Self Description Test (SD)"],
      },
      {
        title: "Day 3 & 4 - GTO Tasks",
        topics: ["Group Discussion", "Group Planning Exercise", "Progressive Group Task", "Half Group Task", "Individual Obstacles", "Command Task", "Final Group Task"],
      },
      {
        title: "Day 5 - Interview & Conference",
        topics: ["Personal Interview with IO", "Conference with Board Members"],
      },
    ],
    schedule: {
      daily: "6:00 AM - 9:00 PM (Full SSB simulation)",
    },
    mentors: ["Brig. Ashok Tandon (Retd.) - Ex-SSB President", "Col. Meera Kapoor (Retd.)", "Maj. Deepak Sharma (Retd.)"],
  },
  {
    slug: "navy",
    title: "Indian Navy (MR/AA/SSR)",
    subtitle: "Navy Recruitment Preparation",
    description: "Complete preparation for Indian Navy recruitment examinations including MR, AA, and SSR with physical fitness training.",
    longDescription: "Join the Indian Navy through various entry schemes including Matric Recruit (MR), Artificer Apprentice (AA), and Senior Secondary Recruit (SSR). Our comprehensive program prepares you for both written examination and physical fitness tests required for naval recruitment.",
    duration: "4 Months",
    eligibility: "10th/12th Pass (as per entry)",
    ageLimit: "17 to 21 years",
    fee: "₹30,000",
    batchSize: "30 Students",
    startDate: "Every Month",
    image: "/placeholder.svg?height=400&width=600",
    icon: "Anchor",
    color: "primary",
    features: [
      "Entry-specific preparation",
      "Mathematics & Science focus",
      "English & General Knowledge",
      "Physical fitness training",
      "Swimming training",
      "Mock tests & analysis",
      "Medical test guidance",
      "Document verification support",
    ],
    syllabus: [
      {
        title: "Mathematics",
        topics: ["Simplification", "Algebra", "Geometry", "Mensuration", "Trigonometry", "Interest", "Time & Work"],
      },
      {
        title: "Science",
        topics: ["Physics Fundamentals", "Chemistry Basics", "Biology Essentials", "General Science"],
      },
      {
        title: "English",
        topics: ["Grammar", "Vocabulary", "Comprehension", "Common Errors"],
      },
      {
        title: "General Knowledge",
        topics: ["Geography", "History", "Polity", "Current Affairs", "Naval Knowledge"],
      },
    ],
    schedule: {
      weekdays: "6:00 AM - 7:30 AM (PT), 9:00 AM - 4:00 PM (Academic)",
      weekends: "Swimming & Mock Tests",
    },
    mentors: ["CPO Rakesh Nair (Retd.)", "Prof. Suresh Kumar", "PO Vinod Sharma (Retd.)"],
  },
  {
    slug: "territorial-army",
    title: "Territorial Army Officer",
    subtitle: "Part-time Army Service",
    description: "Preparation for Territorial Army Officer recruitment examination for working professionals who want to serve the nation.",
    longDescription: "The Territorial Army provides an opportunity for working professionals and civilians to serve the nation in uniform while continuing their primary occupation. Our program prepares candidates for the written examination and subsequent SSB interview.",
    duration: "3 Months",
    eligibility: "Graduates employed in Central/State Govt. or Private Sector",
    ageLimit: "18 to 42 years",
    fee: "₹25,000",
    batchSize: "20 Students",
    startDate: "February & August",
    image: "/placeholder.svg?height=400&width=600",
    icon: "Flag",
    color: "accent",
    features: [
      "Weekend batch option available",
      "Reasoning & Elementary Mathematics",
      "General Knowledge coverage",
      "English proficiency",
      "SSB preparation included",
      "Online doubt sessions",
      "Flexible timing",
      "Working professional friendly",
    ],
    syllabus: [
      {
        title: "Reasoning",
        topics: ["Verbal Reasoning", "Non-verbal Reasoning", "Analytical Reasoning"],
      },
      {
        title: "Elementary Mathematics",
        topics: ["Arithmetic", "Algebra", "Geometry", "Statistics"],
      },
      {
        title: "General Knowledge",
        topics: ["History", "Geography", "Polity", "Economics", "Current Affairs"],
      },
      {
        title: "English",
        topics: ["Grammar", "Vocabulary", "Comprehension", "Usage"],
      },
    ],
    schedule: {
      weekdays: "Evening batches 6:00 PM - 9:00 PM",
      weekends: "Full day sessions 9:00 AM - 5:00 PM",
    },
    mentors: ["Lt. Col. Ajay Singh (Retd.)", "Prof. Ramesh Chandra", "Maj. Neelam Kaur (Retd.)"],
  },
]

export const testimonials = [
  {
    name: "Rahul Sharma",
    role: "NDA 152nd Course",
    content: "Warriors Defence Academy transformed my dream into reality. The structured coaching and personal attention from faculty helped me secure AIR 45 in NDA. Forever grateful!",
    image: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    name: "Priya Singh",
    role: "CDS OTA Entry",
    content: "The SSB preparation at Warriors is unmatched. The mock interviews and GTO practice sessions gave me the confidence I needed. Recommended to all defence aspirants!",
    image: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    name: "Amit Kumar",
    role: "AFCAT Flying Branch",
    content: "From a zero understanding of AFCAT to clearing it in my first attempt - all credit goes to the dedicated faculty here. The study material is comprehensive and up-to-date.",
    image: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    name: "Sneha Patel",
    role: "Indian Navy SSR",
    content: "The physical training program alongside academics prepared me holistically. The faculty understands exactly what the Navy expects from candidates.",
    image: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    name: "Vikram Yadav",
    role: "NDA 153rd Course",
    content: "Best decision of my life joining Warriors Defence Academy. The environment motivates you every day. Now I am living my dream at IMA.",
    image: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    name: "Anjali Mishra",
    role: "CDS IMA Entry",
    content: "The personalized mentoring made all the difference. Each faculty member is committed to your success. Cleared SSB in my second attempt with their guidance.",
    image: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
]

export const mentors = [
  {
    name: "Col. Rajesh Kumar (Retd.)",
    role: "Director & Chief Mentor",
    experience: "28 years in Indian Army",
    specialization: "SSB Interview & Leadership Training",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    name: "Maj. Priya Singh (Retd.)",
    role: "Head - CDS & AFCAT Division",
    experience: "15 years in Indian Air Force",
    specialization: "AFSB & Personality Development",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    name: "Prof. Amit Sharma",
    role: "Head - Mathematics Department",
    experience: "20 years teaching experience",
    specialization: "NDA & CDS Mathematics",
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    name: "Capt. Vikram Yadav",
    role: "Physical Training Instructor",
    experience: "12 years in Indian Navy",
    specialization: "Physical Fitness & Swimming",
    image: "/placeholder.svg?height=300&width=300",
  },
]

export const faqs = [
  {
    question: "What is the eligibility criteria for NDA examination?",
    answer: "For NDA, candidates must be 12th pass or appearing (for Army wing) or 12th pass with Physics and Mathematics (for Air Force and Naval wings). Age should be between 16.5 to 19.5 years. Only unmarried male candidates are eligible.",
  },
  {
    question: "How is the SSB interview conducted?",
    answer: "SSB interview is a 5-day selection process that includes Screening Test (Day 1), Psychological Tests (Day 2), Group Testing Officer Tasks (Day 3-4), and Personal Interview followed by Conference (Day 5). It assesses Officer Like Qualities (OLQs) of candidates.",
  },
  {
    question: "What is the success rate of Warriors Defence Academy?",
    answer: "We are proud to have a success rate of over 65% in SSB interviews, which is significantly higher than the national average. We have produced 2500+ selections in various defence examinations.",
  },
  {
    question: "Do you provide hostel facilities?",
    answer: "Yes, we provide fully furnished hostel facilities with mess, 24/7 security, and all modern amenities. Separate hostels are available for boys and girls with warden supervision.",
  },
  {
    question: "What study materials are provided?",
    answer: "We provide comprehensive study materials including textbooks, previous year papers, practice worksheets, current affairs magazines, and online test series. All materials are regularly updated as per the latest exam patterns.",
  },
  {
    question: "Is physical training mandatory?",
    answer: "Yes, physical training is an integral part of our coaching. We conduct daily PT sessions, running practice, and swimming classes to ensure candidates meet the physical standards required for defence services.",
  },
]

export const stats = [
  { value: "2500+", label: "Selections" },
  { value: "15+", label: "Years Experience" },
  { value: "65%", label: "SSB Success Rate" },
  { value: "50+", label: "Expert Faculty" },
]

export const galleryImages = [
  { src: "/placeholder.svg?height=400&width=600", alt: "Classroom Session", category: "classroom" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Physical Training", category: "training" },
  { src: "/placeholder.svg?height=400&width=600", alt: "SSB Mock Interview", category: "ssb" },
  { src: "/placeholder.svg?height=400&width=600", alt: "GTO Task Practice", category: "ssb" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Library", category: "facilities" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Computer Lab", category: "facilities" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Morning PT", category: "training" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Guest Lecture", category: "events" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Independence Day", category: "events" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Success Celebration", category: "events" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Group Discussion", category: "ssb" },
  { src: "/placeholder.svg?height=400&width=600", alt: "Swimming Pool", category: "facilities" },
]
